### ISSUE TITLE
Feature Request - Customized Email Subject

### ISSUE THREAD

**Issue by jayhding** [ndelitski/rancher-alarms#10]
@ndelitski First of all thanks for the html template support, now I can set ENV `ALARM_EMAIL_TEMPLATE` to use HTEML emails.

Could you also please add support for email subject customisation from environment?

**Comment by ndelitski** [comment]
Sure, I forgot to pass setting with env variable

**Comment by ndelitski** [comment]
hi @JayHaoDing! you can set subject now with env variable `ALARM_EMAIL_SUBJECT`. Templating is supported here so you are able to write smth like "[Rancher] Service #{serviceName} become degraded".
