### ISSUE TITLE
release 0.1.2

### ISSUE THREAD

**Issue by ndelitski** [ndelitski/rancher-alarms#14]
Hey guys! @flaccid  @SydOps  @JayHaoDing Just published new release image labeled `v0.1.2`
Changes:
- #5 Slack integration
- #12 shrink image size with alpine-node
- Support templating + #10
- fixed bugs #7 #4 #2

Will create a ticket for the next upcoming release v0.2.0

**Comment by flaccid** [comment]
@ndelitski fantastic thank you. I will give this a spin today and see if everything is covered. Will open new issue(s) if any problems.
