### ISSUE TITLE
Clarity on filter - whitelist/blacklist | exclusion/inclusion

### ISSUE THREAD

**Issue by flaccid** [ndelitski/rancher-alarms#18]
Can we just have a bit of enhancement in the readme for `filter`?
Just trying to understand if 'whitelist' means exclusion or inclusion of stack/service names to monitor and raise alarms for?

Our particular use case is the exclusion one - we'd like to not monitor and alarm particular stacks or services that we don't care about.

Depending on your point of view here, the definition of whitelist/blacklist | exclusion/inclusion can be on either side.

**Comment by ndelitski** [comment]
Yeah, we absolutely need to support this feature in an environment config. Progam code already has this possibility and it is supported if you are using json config, so i have to extend configuration a little bit. I'll do it today

**Comment by ndelitski** [comment]
@flaccid Implemented whitelist filter in v0.1.4 release, use `ALARM_FILTER` with list of regex values agains `stack/service` names, for example `ALARM_FILTER=app/*,frontend,backend`

**Comment by flaccid** [comment]
@ndelitski thanks! Does that mean if the regex is within `ALARM_FILTER` that they are excluded from monitoring (I think we need a note against it in https://github.com/ndelitski/rancher-alarms/blob/master/README.md#polling-settings)?
