### ISSUE TITLE
Run as an rancher agent

### ISSUE THREAD

**Issue by ndelitski** [ndelitski/rancher-alarms#19]
Container might be started with a rancher-agent label and it will automatically receive credentials with an access to current environment

**Comment by guzmo** [comment]
This sounds really cool :) Id rather start it up inside of the rancher environment and therefore it feels waste to have to set these parameters. Its not possible for it to use the http://rancher-metadata api otherwise?

**Comment by ndelitski** [comment]
You can use http://rancher-metadata without any credentials, but I didn't do it because it hadn't enough information about the service state at that moment, so i call api directly with the api key.
*have to look at new version of rancher-metatada*

**Comment by ndelitski** [comment]
@SydOps @flaccid hey guys no need to pass RANCHER_\* options anymore! v0.1.4 release is here https://github.com/ndelitski/rancher-alarms/blob/master/CHANGELOG.md
