### ISSUE TITLE
State buffer length is always 1

### ISSUE THREAD

**Issue by jayhding** [ndelitski/rancher-alarms#2]
Below codes in monitor.es6 tend to initialise two buffers with given length but both buffers will be created with length as 1.

```
class StateRingBuffer {
  get length() {
    return this._arr.length;
  }
  constructor(length) {
    this._arr = new Array(length);
  }

...

    this._unhealtyStatesBuffer = new StateRingBuffer(this.healthcheck.unhealthyThreshold);
    this._healtyStatesBuffer = new StateRingBuffer(this.healthcheck.healthyThreshold);
...
}
```

Need to change array initialisation method to

```
class StateRingBuffer {
  constructor(length) {
    this._arr = Array.apply( null, { length: length } );
  }
```

**Comment by ndelitski** [comment]
@JayHaoDing Hi Jay! On which version of node can i reproduce this issue?

**Comment by jayhding** [comment]
Hi, I'm using Node 4.2.1

**Comment by jayhding** [comment]
@ndelitski Hi Nick, not sure if this issue can be reproduced from your side?

**Comment by ndelitski** [comment]
seems new array is not iterable until i specify length property, merged https://github.com/ndelitski/rancher-alarms/pull/3
