### ISSUE TITLE
Stack and Service URL have changed since Rancher GA 1.0

### ISSUE THREAD

**Issue by jayhding** [ndelitski/rancher-alarms#4]
Before Rancher GA the URL looks like

```
http://rancher-server/apps/1e118
http://rancher-server/apps/1e118/services/1s657
```

But Rancher GA 1.0 apparently changed the URL to such

```
http://rancher-server/env/1a14/apps/stacks/1e118
http://rancher-server/env/1a14/apps/stacks/1e118/services/1s657
```

Therefore, monitor.es6 needs to be updated to generate correct URL in the email. Thanks.

**Comment by jayhding** [comment]
@ndelitski hi, would you mind to comment if you plan to work on this issue? Thanks!

**Comment by flaccid** [comment]
Possible to kill this one soon?

**Comment by ndelitski** [comment]
@flaccid fixed urls here https://github.com/ndelitski/rancher-alarms/commit/2e562aabb7d037a9f7181ec779b09460769e8d64
